In [2]:
import pandas as pd

df = pd.read_csv('csvFile/user_list.csv')
print(df)

                  REG_DATE SEX_ID  AGE WITHDRAW_DATE PREF_NAME  \
0      2012-03-28 14:14:18      f   25           NaN       NaN   
1      2011-05-18 00:41:48      f   34           NaN       東京都   
2      2011-06-13 16:36:58      m   41           NaN       愛知県   
3      2012-02-08 12:56:15      m   25           NaN       NaN   
4      2011-05-22 23:43:56      m   62           NaN      神奈川県   
...                    ...    ...  ...           ...       ...   
22868  2011-12-12 15:42:56      f   24           NaN       NaN   
22869  2011-08-10 00:49:55      m   41           NaN       京都府   
22870  2012-04-05 12:24:23      f   35           NaN       NaN   
22871  2011-02-20 10:34:22      f   59           NaN       NaN   
22872  2011-02-24 15:43:18      f   38           NaN       埼玉県   

                           USER_ID_hash  
0      d9dca3cb44bab12ba313eaa681f663eb  
1      560574a339f1b25e57b0221e486907ed  
2      e66ae91b978b3229f8fd858c80615b73  
3      43fc18f32eafb05713ec02935e2c2825

In [3]:
datas = df.dropna(subset=["PREF_NAME"])

In [4]:
print(datas)

                  REG_DATE SEX_ID  AGE WITHDRAW_DATE PREF_NAME  \
1      2011-05-18 00:41:48      f   34           NaN       東京都   
2      2011-06-13 16:36:58      m   41           NaN       愛知県   
4      2011-05-22 23:43:56      m   62           NaN      神奈川県   
5      2011-05-27 16:17:19      f   50           NaN       広島県   
6      2011-08-24 23:30:24      m   44           NaN       埼玉県   
...                    ...    ...  ...           ...       ...   
22860  2010-11-16 11:45:48      f   29           NaN       宮城県   
22861  2011-08-16 01:43:50      f   35           NaN       東京都   
22864  2010-12-17 21:17:39      m   42           NaN       長崎県   
22869  2011-08-10 00:49:55      m   41           NaN       京都府   
22872  2011-02-24 15:43:18      f   38           NaN       埼玉県   

                           USER_ID_hash  
1      560574a339f1b25e57b0221e486907ed  
2      e66ae91b978b3229f8fd858c80615b73  
4      dc6df8aa860f8db0d710ce9d4839840f  
5      f430e8302c1fd0915bce0c068ecb2f82

In [5]:
datas = datas[datas.isnull().any(1)]

In [6]:
datas.reset_index(drop=True)

REG_DATE SEX_ID  AGE WITHDRAW_DATE PREF_NAME  \
0      2011-05-18 00:41:48      f   34           NaN       東京都   
1      2011-06-13 16:36:58      m   41           NaN       愛知県   
2      2011-05-22 23:43:56      m   62           NaN      神奈川県   
3      2011-05-27 16:17:19      f   50           NaN       広島県   
4      2011-08-24 23:30:24      m   44           NaN       埼玉県   
...                    ...    ...  ...           ...       ...   
15240  2010-11-16 11:45:48      f   29           NaN       宮城県   
15241  2011-08-16 01:43:50      f   35           NaN       東京都   
15242  2010-12-17 21:17:39      m   42           NaN       長崎県   
15243  2011-08-10 00:49:55      m   41           NaN       京都府   
15244  2011-02-24 15:43:18      f   38           NaN       埼玉県   

                           USER_ID_hash  
0      560574a339f1b25e57b0221e486907ed  
1      e66ae91b978b3229f8fd858c80615b73  
2      dc6df8aa860f8db0d710ce9d4839840f  
3      f430e8302c1fd0915bce0c068ecb2f82  
4      f3722c3232531440308e8017f28b8cdd  
...                                 ...  
15240  7b171a6481a8ddbde17f0de7086576fe  
15241  ee243500b330d41a7a8ba49edc070b7e  
15242  af39e9ffc80ac6fd7b31e0cc66f99ffb  
15243  6ae7811a9c7c58546d6a1567ab098c21  
15244  280f0cedda5c4b171ee6245889659571  

[15245 rows x 6 columns]

In [8]:
import pandas as pd

df = pd.read_csv('csvFile\coupon_list_train.csv')
print(df)

      CAPSULE_TEXT GENRE_NAME  PRICE_RATE  CATALOG_PRICE  DISCOUNT_PRICE  \
0              グルメ        グルメ          50           3000            1500   
1              グルメ        グルメ          51           2080            1000   
2              グルメ        グルメ          50           7000            3500   
3              グルメ        グルメ          50           3000            1500   
4              グルメ        グルメ          50           2000            1000   
...            ...        ...         ...            ...             ...   
19408       ネイル・アイ     ネイル・アイ          65          10000            3500   
19409          グルメ        グルメ          50           5980            2990   
19410          グルメ        グルメ          50           6300            3150   
19411          グルメ        グルメ          50           2400            1200   
19412          グルメ        グルメ          60           6000            2400   

                  DISPFROM              DISPEND  DISPPERIOD   VALIDFROM  \
0      2011-

In [9]:
import numpy as np

size=df["COUPON_ID_hash"].size
vectors=np.identity(size)
dictionary_coupones={}

for i in range(size):
 dictionary_coupones[df.loc[i,"COUPON_ID_hash"]]=vectors[i] 

In [10]:
import pandas as pd

df2 = pd.read_csv('csvFile\coupon_area_train.csv')
print(df2)

       SMALL_AREA_NAME PREF_NAME                    COUPON_ID_hash
0                   埼玉       埼玉県  6b263844241eea98c5a97f1335ea82af
1                   千葉       千葉県  cc031f250e8bad1e24060263b9fc0ddd
2                   千葉       千葉県  ba5e9b7453ca52ff711635a5d2e8102d
3                   千葉       千葉県  3e1ffbedca3569f9e8032d401e8cb4e6
4                   千葉       千葉県  782934b6c815b4030ea204eef7d4a734
...                ...       ...                               ...
138180              新潟       新潟県  fe334f1a5e0dc54eca76b9dd9559661b
138181  新宿・高田馬場・中野・吉祥寺       東京都  8dc11b257cb1c5b98e7b7c66d9b2b779
138182      渋谷・青山・自由が丘       東京都  b15e2d7619c3fd9c6be567c971bdf4f4
138183     銀座・新橋・東京・上野       東京都  e1141a4b2798450f36e40090659c0b07
138184  新宿・高田馬場・中野・吉祥寺       東京都  79303de03e3af7105cded55960d62ac3

[138185 rows x 3 columns]


In [15]:
import pandas as pd

cp = pd.read_csv('csvFile\coupon_detail_train.csv')
print(cp)

        ITEM_COUNT               I_DATE SMALL_AREA_NAME  \
0                1  2012-03-28 15:06:06              兵庫   
1                1  2011-07-04 23:52:54     銀座・新橋・東京・上野   
2                1  2011-07-16 00:52:49       恵比寿・目黒・品川   
3                1  2011-07-16 00:54:53       恵比寿・目黒・品川   
4                1  2011-07-16 00:55:52       恵比寿・目黒・品川   
...            ...                  ...             ...   
168991           1  2012-02-07 12:14:50       池袋・神楽坂・赤羽   
168992           1  2012-02-28 15:43:21     銀座・新橋・東京・上野   
168993           1  2012-03-19 12:11:16     銀座・新橋・東京・上野   
168994           2  2012-04-12 12:27:34  新宿・高田馬場・中野・吉祥寺   
168995           1  2012-05-09 12:12:26  新宿・高田馬場・中野・吉祥寺   

                         PURCHASEID_hash                      USER_ID_hash  \
0       c820a8882374a4e472f0984a8825893f  d9dca3cb44bab12ba313eaa681f663eb   
1       1b4eb2435421ede98c8931c42e8220ec  560574a339f1b25e57b0221e486907ed   
2       36b5f9ba46c44b65587d0b16f2e4c77f  560574a339f1b25

In [17]:
users = pd.read_csv('csvFile/user_list.csv')

In [18]:
X=[] 
training_set_size=0 
for i in range(int(round(0.3*cp["COUPON_ID_hash"].size))):
  index=users.USER_ID_hash[users.USER_ID_hash == cp.loc[i,"USER_ID_hash"]].index.tolist() 
  
  if index!=[]:
    training_set_size+=1
    x1=int(users.loc[index,"AGE"])
    if str(users.loc[index,"SEX_ID"]).split()[1]=='f':
      x2=1
    else:
      x2=0
      
    X.append([x1,x2])

In [19]:
print(training_set_size)
print(X)

50699
[[25, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [34, 1], [41, 0], [25, 0], [25, 0], [25, 0], [25, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [62, 0], [50, 1], [44, 0], [44, 0], [44, 0], [44, 0], [44, 0], [44, 0], [40, 1], [40, 1], [40, 1], [40, 1], [40, 1], [40, 1], [40, 1], [40, 1], [47, 0], [47, 0], [47, 0], [47, 0], [47, 0], [47, 0], [47, 0], [47, 0], [47, 0], [47, 0], [47, 0], [47, 0], [47, 0], [31, 0], [31, 0], [41, 1], [41, 1], [41, 1], [41, 1], [31, 1], [31, 1], [31, 1], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [48, 0], [32

In [20]:
import pandas as pd

cp = pd.read_csv('csvFile\coupon_detail_train.csv')
print(cp)

        ITEM_COUNT               I_DATE SMALL_AREA_NAME  \
0                1  2012-03-28 15:06:06              兵庫   
1                1  2011-07-04 23:52:54     銀座・新橋・東京・上野   
2                1  2011-07-16 00:52:49       恵比寿・目黒・品川   
3                1  2011-07-16 00:54:53       恵比寿・目黒・品川   
4                1  2011-07-16 00:55:52       恵比寿・目黒・品川   
...            ...                  ...             ...   
168991           1  2012-02-07 12:14:50       池袋・神楽坂・赤羽   
168992           1  2012-02-28 15:43:21     銀座・新橋・東京・上野   
168993           1  2012-03-19 12:11:16     銀座・新橋・東京・上野   
168994           2  2012-04-12 12:27:34  新宿・高田馬場・中野・吉祥寺   
168995           1  2012-05-09 12:12:26  新宿・高田馬場・中野・吉祥寺   

                         PURCHASEID_hash                      USER_ID_hash  \
0       c820a8882374a4e472f0984a8825893f  d9dca3cb44bab12ba313eaa681f663eb   
1       1b4eb2435421ede98c8931c42e8220ec  560574a339f1b25e57b0221e486907ed   
2       36b5f9ba46c44b65587d0b16f2e4c77f  560574a339f1b25

In [21]:

T=[]
for i in range(int(round(0.3*cp["COUPON_ID_hash"].size))):
  index=users.USER_ID_hash[users.USER_ID_hash == cp.loc[i,"USER_ID_hash"]].index.tolist() 
  
  if index!=[]:
 
    t= dictionary_coupones[cp.loc[i,"COUPON_ID_hash"]]
    
   
    T.append(t)

In [22]:
print(T)

[array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 

In [56]:

num_random_users=25 

for i in range(num_random_users):

  ge=random.randint(1,100)
  sex=np.random.choice(2) 
  if sex==0:
    sex_str="M"
  else:
    sex_str="F"
    
  arr=np.array([[age,sex]])
  sum=0

  if sum>0.1:
    guarantee="YES"
  else:
    guarantee="NO"

  result = np.where(arr == np.amax(arr))
  size=df["COUPON_ID_hash"].size
  vector=np.zeros(size)
  vector[result[1][0]]=1
print(result)
print(vector)
print(arr)

(array([0], dtype=int64), array([0], dtype=int64))
[1. 0. 0. ... 0. 0. 0.]
[[11  0]]


In [33]:
import random
age=random.randint(1,100)
sex=np.random.choice(2) 
if sex==0:
  sex_str="M"
else:
  sex_str="F"

arr=np.array([[age,sex]])
sum=0

if sum>0.1:
  guarantee="YES"
else:
  guarantee="NO"

max_prob=np.amax(arr)
result = np.where(arr == np.amax(arr))
size=df["COUPON_ID_hash"].size 
vector=np.zeros(tamaño)
vector[result[1][0]]=1

print("AGE: ", age)
print("SEX: ", sex_str)
print("Coupon most probable to be sold: ", [k for k,v in  dictionary_coupones.items() if np.array_equal(v,vector)])
print('Prob. of selling the coupon most probable to be sold: ', round(max_prob*100,3),"%")
print('Prob. of selling any of the 10 coupons most probable to be sold: ', round(sum*100,3),"%")
print("Almost Ensured sell?", guarantee)

AGE:  11
SEX:  F
Coupon most probable to be sold:  ['6b263844241eea98c5a97f1335ea82af']
Prob. of selling the coupon most probable to be sold:  1100 %
Prob. of selling any of the 10 coupons most probable to be sold:  0 %
Almost Ensured sell? NO
